config/routes.rb
Ranking::Application.routes.draw do
  
  resources :members
  resources :sessions, :only => [:new, :create, :destroy]
  
  root :to => "sessions#new"
  
  match '/signup', :to => "members#new"
  match '/about', :to => "pages#about"
  match '/contact', :to => "pages#conract"
  match '/signout', :to => "sessions#destroy"
  
  match '/saturdayschool/home', :to => "pages#home"
  

end

app/models/group.rb
# == Schema Information
# Schema version: 20110613164425
#
# Table name: groups
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Group < ActiveRecord::Base
  attr_accessible :name
  
  has_many :memberships
  has_many :member, :through => :memberships
end

app/models/member.rb
# == Schema Information
# Schema version: 20110614134645
#
# Table name: members
#
#  id                 :integer         not null, primary key
#  first_name         :string(255)
#  last_name          :string(255)
#  email              :string(255)
#  date_of_birth      :date
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'

class Member < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :first_name,        :presence     => true,
                                :length       => { :maximum => 50 }
  
  validates :last_name,         :presence     => true,
                                :length       => { :maximum => 50 }
                               
  validates :email,             :presence     => true,
                                :format       => { :with => email_regex },
                                :uniqueness   => { :case_sensitive => false }
  
  # Automatically create the virtual accessible attribute 'password confirmation'
  validates :password,        :presence     => true,
                              :confirmation => true,
                              :length       => { :within => 6..40 }
                              
  has_many :memberships
  has_many :group, :through => :memberships
  
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    member = find_by_email(email)
    return nil if member.nil?
    return member if member.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    member = find_by_id(id)
    (member && member.salt == cookie_salt) ? member : nil
  end

  private
  
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
end

app/models/membership.rb
# == Schema Information
# Schema version: 20110613164425
#
# Table name: memberships
#
#  id         :integer         not null, primary key
#  member_id  :integer
#  group_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Membership < ActiveRecord::Base
  attr_accessible :member_id, :group_id
  
  belongs_to :member
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @title = "Sign Up"
    @member = Member.new
  end
  
  def create
    @member = Member.new(params[:member])
    
    if @member.save
      sign_in @member
      redirect_to @member
    else
      @title = "Sign Up"
      render :new
    end
  end
  
  def show
    @member = Member.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = 'Home'
  end

  def signup
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @title = "Sign in"
  end
  
  def create
    member = Member.authenticate(params[:session][:email],
                                 params[:session][:password])
    if member.nil?
      flash.now[:error] = "Invalid email/password combination"
      @title = "Sign in"
      render 'new'
    else
      sign_in member
      redirect_to member
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  
  def title
    base_title = "Rank Your Team-mates"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(member)
    cookies.permanent.signed[:remember_token] = [member.id, member.salt]
    current_member = member
  end
  
  def sign_out
    cookies.delete(:remember_token)
    current_member = nil
  end
  
  def current_member=(member)
    @current_member = member
  end

  def current_member
    @current_member ||= member_from_remember_token
  end
  
  def signed_in?
    !current_member.nil?
  end
  
  private
    
    def member_from_remember_token
      Member.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div id="footerline"></div>
	<div style="height: 21px; padding: 12px 4px 6px 0">
		<a>footer</a>
	</div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	<% if signed_in? %>
		<div style="height: 21px; padding: 12px 4px 6px 0">
			<%= link_to "Sign out", signout_path, :method => :delete %>
		</div>
	<% else %>
		<div style="height: 21px; padding: 12px 4px 6px 0">
			<%= link_to "Sign up", signup_path %>
		</div>
	<% end %>	
	<div id="headerline"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  	<%= csrf_meta_tag %>
  	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
	<!--[if lt IE 8]>
		<%= stylesheet_link_tag 'blueprint/ie' %>
	<![endif]-->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header'%>
		<div>
			<%= yield %>
		</div>
		<%= render 'layouts/footer'%>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/members/new.html.erb
<h1>Sign me up!</h1>

<p>Step 1. become a member.   Step 2. validate your email address. Step 3. Join or add groups.</p>

<%= simple_form_for @member do |f| %>
  <%= f.input :first_name, :label => "first name" %>
  <%= f.input :last_name, :label => "last name" %>	
  <%= f.input :email, :label => "email" %>
  <%= f.input :password, :label => "password" %>
  <%= f.input :password_confirmation, :label => "confirmation" %>
  <%= f.button :submit, :value => "Sign up" %>
<% end %>

app/views/members/show.html.erb
<div style="padding: 50px 0 0 0">
<h1><%= @member.first_name %> <%= @member.last_name %> <p style="font-size: 15px">(<%= @member.email %>) </p></h1>
</div>

app/views/pages/home.html.erb
<div style="height: 40px"></div>
<div class="sslogo">
	<% logo = image_tag("rnkd_logo.png") %> <!--sslogo.jpg-->
	<%= link_to logo, root_path %>
</div>
<div>
	<div style="width: 50%">
	<table>
	<tr>
		<td>
			<input type="text" value="email address" class="textbox" style="margin: 0 -10px 0 160px; width: 150px"> 
		</td>
		<td>	
			<input type="text" value="password" class="textbox" style="margin: 0 -10px 0 0; width: 150px">
		</td>
		<td>
			<span class="login_button">login</span>
		</td>	
	</tr>
	
	</table>
	</div>
</div>

<div style="height: 40px"></div>